name: Pull Garmin data

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'NOTES.txt'
      - 'README.md'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 11,23 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas datetime selenium
    - name: Pull data
      run: |
        python vo2max_longevity/get_data.py
      env:
        GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
        GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
    - name: Commit any changes to data files
      run: |
        git config --local user.name "harveybarnhard"
        git config --local user.email "${{ secrets.USER_EMAIL }}"
        git add ./data
        git commit -m "Auto-updating Garmin data"
    - name: Push any committed changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        force: true
